# - name: lab 3 Both Hosts
#   hosts: virtualmachines
#   tasks:
#   - name: wget install
#     become: true
#     package: 
#       name: wget
#       state: present
#       update_cache: true
#   - name: install unzip on hosts -b
#     become: yes
#     package:
#       name: unzip
#       state: present
#       update_cache: true
#     when: ansible_host == '35.177.231.51'
#   - name: install nginx on host -name
#     become: yes
#     package: 
#       name: nginx
#       state: present
#       update_cache: true
#     when: ansible_host == '18.170.30.235'
#   - name: install unzip from all machines
#     become: true
#     package: 
#       name: unzip
#       state: absent
#       update_cache: true


- name: Install VM01
  hosts: VM01
  tasks:
    - name: Install nginx
      become: yes
      apt:
        name: nginx
        state: present
      register: nginx_install

    - name: HTML on VM01
      become: yes
      copy:
        src: "{{ playbook_dir }}/index.nginx-debian.html"
        dest: /var/www/html/index.nginx-debian.html

    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: restarted

    - name: Remove apt lock file if it exists
      become: yes
      file:
        path: /var/lib/apt/lists/lock
        state: absent

    - name: Install prerequisites for Docker repo
      become: yes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install Docker CE
      become: yes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes

    - name: Install prerequisites for docker-compose
      become: yes
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - virtualenv

    - name: Install docker-compose
      become: yes
      pip:
        name: docker-compose

    - name: Ensure Docker is started
      become: yes
      service:
        name: docker
        state: started

- name: setup VM02
  hosts: VM02
  become: yes
  tasks:
    - name: Install Docker on VM02
      shell: curl https://get.docker.com | sudo bash
