
- name: create dev group
  group:
    name: devs
    state: present

- name: add user with your name
  user:
    name: claire
    group: devs
    state: present

- name: install zsh shell
  package:
    name: zsh
    state: absent

- name: install nginx
  package:
    name: nginx
    state: absent

- name: replace html
  copy:
    src: files/index.html
    dest: /var/www/html/index.nginx-debian.html
  notify: restart nginx

- name: Install prerequisites for Docker repo
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: absent
    update_cache: true

# - name: Add Docker GPG key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg

# - name: Add Docker APT repository
#   apt_repository:
#     repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Install prerequisites for docker-compose
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - virtualenv
    state: absent

# - name: Install docker-compose
#   pip:
#     name: docker-compose
#     state: absent

# - name: Ensure Docker is started
#   service:
#     name: docker
#     state: started

- name: dependancies (java)
  package: 
    name: openjdk-11-jdk
    state: present

- name: add jenkins apt repo key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    state: present

- name: add jenkins apt repo
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian binary/
    state: present

- name: ensure jenkins is install
  apt: 
    name: jenkins
    state: present
    update_cache: true

- name: ensure jenkins is running
  service: 
    name: jenkins
    state: started
    enabled: true



